# Core Colors
background            #111318
foreground            #e2e2e9
selection_foreground  #aac7ff
selection_background  #0a305f
cursor                #aac7ff
cursor_text_color     #111318

# Regular Colors
color0  #111318
color1  #ffb4ab
color2  #aac7ff
color3  #dcbce0
color4  #d6e3ff
color5  #dae2f9
color6  #bec6dc
color7  #e2e2e9

# Bright Colors
color8  #37393e
color9  #ffb4ab
color10 #aac7ff
color11 #dcbce0
color12 #d6e3ff
color13 #dae2f9 
color14 #bec6dc
color15 #e2e2e9
