$terminal = kitty
$fileManager = nautilus
$launcher = nucleus ipc call launcher toggle
$wallpaperSelector = nucleus ipc call wallpaperSelector toggle
$powermenu = nucleus ipc call powermenu toggle
$lockscreen = nucleus ipc call lockscreen lock
$sidebarRight = nucleus ipc call sidebarRight toggle
$sidebarLeft = nucleus-shell ipc call sidebarLeft toggle
$browser = vivaldi
$screenshot = nucleus ipc call screen capture  
$gss = bash -c 'grim -g "$(slurp)" /tmp/shot.png && cp /tmp/shot.png ~/Pictures/Screenshots/screenshot-$(date +%s).png && wl-copy < /tmp/shot.png'
