input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0

    touchpad {
        natural_scroll = false
        # Enable two-finger tap for right-click
        tap-to-click = true
        # Use 'clickfinger' for two-finger click or 'areas' for bottom-right
        clickfinger_behavior = true 
    }
}

